name: bicep_build
on: [push]
jobs: 
  bicep-build:
    name: bicep-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run bicep lint
        uses: synergy-au/bicep-lint-action@v1
        with:
          analyse-all-files: 'true'
      - name: Run bicep build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: azure/main.bicep
          outputFilePath: azure/marketplace/azureDeploy.json
      - name: Add new template
        run: git add azure/marketplace/azureDeploy.json
      - name: Commit the templates
        uses: EndBug/add-and-commit@v9
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default_author: github_actions